# Generated by Django 3.1 on 2021-01-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atricle',
            new_name='Article',
        ),
    ]
