# Generated by Django 3.1 on 2021-01-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demofirst', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_test',
            new_name='question_text',
        ),
    ]
